---
name: Copa Node Tally Sync app builder
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        required: true
        default: dev
      bumpType:
        description: Update type(major, minor, patch)
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: patch
      version:
        description: Version to be released
        required: true
        default: 0.0.1
      changelog:
        required: false
        description: Changelog to be included
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: bluecopa/tally-to-xl
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.PAT }}
      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=${{github.event.inputs.changelog}}" >> $GITHUB_OUTPUT
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: checking where i am
        run: pwd && ls -la
      - name: Creating a github release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: tally2xl-v0.0.1
          tag_name: tally-to-xl
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Package into node binary
        run: npm i && npm run package
      - name: check folder contents
        run: cd bin && ls -la
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: /bin/tally2xl-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
