name: Copa Node Tally Sync app builder
on:
  workflow_dispatch:
    tag: 
      - v*
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: dev
      bumpType:
        description: "Update type(major, minor, patch)"
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: patch
      changelog:
        required: false
        description: "Changelog to be included"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "bluecopa/tally-to-xl"
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.PAT }}
      # for projects that use labels and PRs,
      # try https://github.com/mikepenz/release-changelog-builder-action instead
      # TODO: use API to collect commit messages
      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=${{github.event.inputs.changelog}}" >> $GITHUB_OUTPUT
      - name: Node.js setup
        uses: actions/setup-node@v3
        # NOTE: enterprise developers may hard code a version
        with:
          node-version: latest
          # node-version-file: '.nvmrc'
      
      - name: version
        run: echo "::set-output name=version::$(./bin --version)"
      - name: checking where i am
        run: pwd && ls -la
      - name: Package into node binary
        run: npm i && npm run package && cd /bin && ls -la
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tally-to-xl-v0.0.1
          files: |
            bin/tally2xl-linux
            bin/tally2xl-macos
            bin/tally2xl-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
