name: Copa Node Tally Sync app builder
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: dev
      bumpType:
        description: "Update type(major, minor, patch)"
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: patch
      changelog:
        required: false
        description: "Changelog to be included"
jobs:
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: "bluecopa/tally-to-xl"
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.PAT }}
    # for projects that use labels and PRs,
    # try https://github.com/mikepenz/release-changelog-builder-action instead
    # TODO: use API to collect commit messages
    - name: Build Changelog
      id: build_changelog
      run: echo "changelog=${{github.event.inputs.changelog}}" >> $GITHUB_OUTPUT
    - name: Node.js setup
      uses: actions/setup-node@v3
      # NOTE: enterprise developers may hard code a version
      with:
        node-version: latest
    - name: Package into node binary
      run: npm i && npm run package
    - name: check folder contents
      run: cd bin && ls -la
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin
        asset_name: tally2xl-linux
        asset_content_type: application/gzip
    - name: upload darwin artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin
        asset_name: tally2xl-macos
        asset_content_type: application/gzip
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin
        asset_name: tally2xl-win.exe
        asset_content_type: application/zip