name: Copa Test version finder
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: "Update type(major, minor, patch)"
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: patch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Bump version
        id: bump_version
        run: |
          echo "version=$(npx -y run-func .public/getVersion.js getVersionParseRelease ${{ github.event.inputs.bumpType }})" >> $GITHUB_OUTPUT
      - name: Print previous
        run: |
          echo ${{steps.bump_version.outputs.version}}
