name: Copa Desktop app builder
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Update type(major, minor, patch)'
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: patch
jobs:
  release:
    runs-on: ubuntu-latest
  steps:
    - name: Bump version
      id: bump_version
      run: |
        version=$(npx -y run-func .public/getVersion.js getVersionParseRelease 'patch') && |
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Print previous
      run: |
        echo ${{steps.bump_version.version}}
      

    